Feature/reaction story
200Lab-Capybara/instagram pull request #49
Opened 2024-06-26 16:00 UTC by hxuan190

2024-06-26 16:09 UTC, nghiatrann0502 requested changes
Tương đối Ok rồi đó. Chỉnh lại xíu anh nghĩ là ngon haha

2024-06-26 16:09 UTC, nghiatrann0502 commented on app/infras/services/reaction_story/repository/mysql/create_reaction_story.go
> +		UpdatedAt: nil,
UpdatedAt bằng với CreatedAt khi khởi tạo luôn nha em

2024-06-26 16:09 UTC, nghiatrann0502 commented on app/infras/services/reaction_story/repository/mysql/create_reaction_story.go
> +		UpdatedAt: nil,
Chỗ này anh tạo ở ngoài usecase luôn ó, không nên tạo trong này đâu. Mốt em muốn thêm em kiếm cái chỗ này thêm là ngáo luôn ó

2024-06-26 16:09 UTC, nghiatrann0502 commented on app/infras/services/reaction_story/repository/mysql/has_been_reaction_story.go
> +		UpdatedAt: nil,
Time chỗ này luôn nha

2024-06-26 16:09 UTC, nghiatrann0502 commented on app/infras/services/reaction_story/repository/mysql/create_reaction_story.go
> +		UpdatedAt: nil,
Mà giờ để đây chắc cũng khong sao đâu

2024-06-26 16:09 UTC, nghiatrann0502 commented on app/infras/services/reaction_story/transport/http/reaction_story_handler.go
> +	uc reactionstoryusecase.InsertReactionStoryUseCase
Tên usecase hơi conflict thì phải. Anh nghĩ là react story đúng hơn là insert á

2024-06-26 16:09 UTC, nghiatrann0502 commented on app/internals/services/reaction_story/usecase/create_reaction_story.go
> +func NewInsertReactionStoryUseCase(reactRepo IReactionStoryRepository, storyRepo getStoryRepository, pubsub pubsub.MessageBroker) InsertReactionStoryUseCase {
Chỗ này đổi tên lại xíu là ok nè

2024-06-26 16:09 UTC, nghiatrann0502 commented on app/internals/services/reaction_story/usecase/create_reaction_story.go
> +		postMessage := pubsub.NewAppMessage(&userId, common.ReactedPostTopic, map[string]interface{}{
reactStoryMessage chứ 
Tên Topic là ReactedStoryTopic chứ ta

2024-06-26 16:09 UTC, nghiatrann0502 commented on app/internals/services/reaction_story/usecase/create_reaction_story.go
> +			"post_id":    storyId,
thay post_id thành story_id nha

2024-06-26 16:12 UTC, hxuan190 commented on app/internals/services/reaction_story/usecase/create_reaction_story.go
> +			"post_id":    storyId,
ủa ủa

2024-06-26 16:12 UTC, hxuan190 commented on app/internals/services/reaction_story/usecase/create_reaction_story.go
> +		postMessage := pubsub.NewAppMessage(&userId, common.ReactedPostTopic, map[string]interface{}{
ủa ủa

2024-06-28 03:28 UTC, nghiatrann0502 requested changes
Đổi lại cái UC nha

2024-06-28 03:28 UTC, nghiatrann0502 commented on app/infras/services/reaction_story/transport/http/reaction_story_handler.go
> +	uc reactionstoryusecase.ReactionStoryUseCase
Chỗ này ghi chi tiết cái UC ra nè. Mốt thêm là khong viết cái UC này làm gì luôn á

2024-06-29 04:20 UTC, merged