Feature/create hastag for post
200Lab-Capybara/instagram pull request #54
Opened 2024-06-28 11:11 UTC by tranvuquanganhRMIT87

2024-06-29 04:34 UTC, nghiatrann0502 requested changes
Em fix mấy cái anh nói trước nha. Em đang trỏ nhầm vào main luôn á. Trỏ vào dev nha

2024-06-29 04:34 UTC, nghiatrann0502 commented on app/infras/services/hashtag/infras/repository/mysql/MapHashTag.go
> +func (m *mySQLStorage) MapHashTag(ctx context.Context, postID uuid.UUID, hashtag hashtagmodel.Hashtag) (bool, error) {
Chỗ này nhiều em có thể dùng DTO cho gọn nè

2024-06-29 04:34 UTC, nghiatrann0502 commented on app/infras/services/hashtag/infras/repository/mysql/MapHashTag.go
> +	if err := db.Table(hashtagmodel.HashtagPost{}.TableName()).Create(&newHashTagPost).Error; err != nil {
newHashTagPost có cái TableName luôn ó

2024-06-29 04:34 UTC, nghiatrann0502 commented on app/infras/services/hashtag/infras/repository/mysql/create_new_hashtag.go
> +		return false, err
Chưa bọc Error lại nè

2024-06-29 04:34 UTC, nghiatrann0502 commented on app/infras/services/hashtag/infras/repository/mysql/get_hashtag.go
> +	if err := m.db.GetConnection().Table("hashtags").Where("Hashtag IN ?", hashtagSlice).Find(&hashtags).Error; err != nil {
Không dùng string cho table name vậy nha. Nên dùng ra Tablename á

2024-06-29 04:34 UTC, nghiatrann0502 commented on app/internals/services/hashtag/model/hashtag.go
> +			nonNullHashtags = append(nonNullHashtags, sluggedTag)
Chỗ này tối ưu được nè. append này nó đang O(N) => tổng hàm này em đang là O(N^2) luôn ó

2024-06-29 04:34 UTC, nghiatrann0502 commented on app/internals/services/hashtag/model/hashtag.go
> +	var hashtagSlice []Hashtag
Chỗ này em tối ưu được luôn nè

2024-06-29 04:34 UTC, nghiatrann0502 commented on app/internals/services/hashtag/usecase/adding_hashtag.go
> +	existedHashtags, err := u.creatingHashTagRepository.GetHashTags(ctx, validNullHashtagsString)
Em chưa check err nè

2024-06-29 04:34 UTC, nghiatrann0502 commented on app/internals/services/hashtag/usecase/adding_hashtag.go
> +	validNullHashtag, err := hashtagFormat.HashTagConvert(ctx, validNullHashtagsString)
Chỗ này cũng chưa check error nè

2024-06-29 04:34 UTC, nghiatrann0502 commented on app/internals/services/hashtag/usecase/adding_hashtag.go
> +			_, creatingHashtagErr := u.creatingHashTagRepository.CreateHashTag(ctx, newHashTag)
chỗ này sai nè. Em đang đi loop db để tạo luôn á. Không được nha

2024-06-30 04:33 UTC, tranvuquanganhRMIT87 commented on app/infras/services/hashtag/infras/repository/mysql/get_hashtag.go
> +	if err := m.db.GetConnection().Table("hashtags").Where("Hashtag IN ?", hashtagSlice).Find(&hashtags).Error; err != nil {
oke r anh nha

2024-06-30 05:38 UTC, nghiatrann0502 commented on app/infras/services/hashtag/infras/repository/mysql/get_hashtag.go
> +	if err := m.db.GetConnection().Table(hashtag.TableName()).Where("Hashtag IN ?", hashtagSlice).Find(&hashtags).Error; err != nil {
Từ từ. Chỗ này là cái [] sao có table name được ta

2024-06-30 09:21 UTC, tranvuquanganhRMIT87 commented on app/internals/services/hashtag/usecase/adding_hashtag.go
> +			_, creatingHashtagErr := u.creatingHashTagRepository.CreateHashTag(ctx, newHashTag)
hmm cái chỗ này nè là em loop qua cái string hashtags mà input dô thôi à, chớ hông có loop db anh ơi, ái validNullHashtag là em lấy từ mà user input dô ý

2024-06-30 16:22 UTC, nghiatrann0502 commented on app/internals/services/hashtag/usecase/adding_hashtag.go
> +			_, creatingHashtagErr := u.creatingHashTagRepository.CreateHashTag(ctx, newHashTag)
Chỗ này theo anh hiểu là em đang loop đi để xem thằng nào chưa có thì đi tạo. 
Mà hàm tạo xuống DB em nằm đây luôn nên là nó loop xuống DB luôn chứ ta

2024-07-01 07:38 UTC, closed without merging